arb-dir: lib/src/utils/language/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-dir: lib/src/utils/language/gen
output-class: AppLocalizations
synthetic-package: false
format: true